id: QmcuVuaiearfSjnUZDKbRb1J7iCWsvQCzkDgHFMT4ifj2X
description: Returns pong to a ping over http
tags: []
source: .
trigger:
    type: http
    method: GET
    paths:
        - /ping
domains:
    - GeneratedDomain
execution:
    timeout: 20s
    memory: 20MB
    call: ping
