id: QmcuVuaiearfSjnUZDKbRb1J7iCWsvQCzkDgHFMT4ifj2X
description: Returns pong to a ping over http
tags: []
source: .
trigger:
    type: https
    method: GET
    paths:
        - /ping
domains:
    - GeneratedDomain
execution:
    timeout: 10s
    memory: 10MB
    call: ping
